# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FrameworksCourseApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FrameworksCourseApp

  pod 'GoogleMaps'
  pod 'RealmSwift'
  pod 'RxSwift'
  pod 'RxCocoa'

  target 'FrameworksCourseAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FrameworksCourseAppUITests' do
    # Pods for testing
  end

end
